version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=change_this_in_production
      - JWT_SECRET_KEY=change_this_in_production
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/securechat

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=securechat
    ports:
      - "5432:5432"

volumes:
  postgres_data: